version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "npm"
